# Generated by Django 4.2.4 on 2023-08-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(verbose_name='place')),
                ('action', models.TextField(verbose_name='action')),
                ('time', models.TimeField(verbose_name='time')),
                ('is_pleasant', models.BooleanField(verbose_name='is_pleasant')),
                ('is_public', models.BooleanField(verbose_name='is_public')),
                ('exec_time', models.PositiveIntegerField(verbose_name='exec_time')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='period')),
                ('award', models.TextField(verbose_name='award')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit_tracker.habit', verbose_name='related_habit')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
                'ordering': ('owner',),
            },
        ),
    ]
